# Generated by Django 5.0.6 on 2026-09-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='utility_type',
            field=models.CharField(choices=[('water', 'Вода'), ('gas', 'Газ'), ('electricity', 'Електрика')], max_length=50),
        ),
        migrations.AlterField(
            model_name='utilityreading',
            name='utility_type',
            field=models.CharField(choices=[('water', 'Вода'), ('gas', 'Газ'), ('electricity', 'Електрика')], max_length=50),
        ),
    ]
