# Generated by Django 5.0.6 on 2026-09-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_tariff_utility_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityreading',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
